---
- name: epel repo
  dnf:
    pkg: epel-release

- name: set ansible user
  user:
    name: ansible
    generate_ssh_key: true
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
    comment: "Ansible User"

- name: ensure remote tmp directory exists
  file:
    path: "{{ remote_tmp }}"
    state: directory
    mode: '0700'
    owner: ansible
    group: ansible

- name: passwordless root in sudoers file
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^ansible ALL\='
    line: 'ansible ALL=(ALL) NOPASSWD:ALL'
    validate: 'visudo -cf %s'
  tags: notest

- name: "ensure python{{ python_v }} and required packages are installed"
  dnf:
    name: "{{ item }}"
  loop:
    - "python{{ python_v }}"
    - "python{{ python_v }}-pip"
    - "{{ controller_pkgs }}"

- name: ensure pip packages and ansible are installed for the ansible user
  pip:
    name: "{{ item }}"
    extra_args: --user
    executable: "pip{{ python_v }}"
  loop: "{{ pip_pkgs }}"
  become_user: ansible

- name: ensure dirs /etc/ansible and /var/log/ansible exists
  file:
    path: "{{ item }}"
    state: directory
    mode: '0700'
    owner: ansible
    group: ansible
  loop:
    - /etc/ansible
    - /var/log/ansible

- name: set ansible config and logrotate
  template:
    src: "{{ item.src }}"
    mode: "{{ item.mode }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    dest: "{{ item.dest }}"
  loop:
    - src: ansible.cfg.j2
      mode: '0700'
      owner: ansible
      group: ansible
      dest: /etc/ansible/ansible.cfg
    - src: logrotate.j2
      mode: '0644'
      owner: root
      group: root
      dest: /etc/logrotate.d/ansible
